# any structural changes here should also be mirrored in deploy_templates/config/anzard_config.yml

defaults: &defaults
  password_reset_email_sender: pwd-reset@intersect.org.au
  account_request_user_status_email_sender: account-status@intersect.org.au
  account_request_admin_notification_sender: account-request@intersect.org.au
  batch_files_root: "/data/anzard-uploads"
  batch_reports_path: "/data/anzard-uploads/reports"
  days_of_failed_batches_to_keep: 15

development:
  <<: *defaults
  batch_files_root: ":rails_root/tmp"
  batch_reports_path: "tmp"

test:
  <<: *defaults
  batch_files_root: ":rails_root/tmp"
  batch_reports_path: "tmp"

production:
  <<: *defaults

staging:
  <<: *defaults

qa:
  <<: *defaults
