defaults: &defaults
  password_reset_email_sender: no-reply@unsw.edu.au
  account_request_user_status_email_sender: no-reply@unsw.edu.au
  account_request_admin_notification_sender: no-reply@unsw.edu.au
  batch_files_root: "/data/anznn-uploads"
  batch_reports_path: "/data/anznn-uploads/reports"
  days_of_failed_batches_to_keep: 15

development:
  <<: *defaults
  batch_files_root: ":rails_root/tmp"
  batch_reports_path: "tmp"

test:
  <<: *defaults
  batch_files_root: ":rails_root/tmp"
  batch_reports_path: "tmp"

production:
  <<: *defaults

staging:
  <<: *defaults

qa:
  <<: *defaults
